name: emp_dept_dbt

version: '1.0.0'

profile: 'emp_dept_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  emp_dept_dbt:

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    datamarts:
      +materialized: table

    analytics:
      +materialized: view

seeds:
  emp_dept_dbt:
    +schema: seed